name = "WinKnownPaths"
uuid = "7ef17fd6-a797-4899-824e-453c4c44979c"
authors = ["Mustafa Mohamad <mus-m@outlook.com> and contributors"]
version = "0.1.2"

[deps]
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
